"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { companies, contacts, deals, notes, emails, calls, initialTasks } from "@/data/seed";

const nav = [["overview","⌂"],["companies","▥"],["contacts","▣"],["deals","▱"],["tasks","☑"],["activity","◉"],["analytics","▥"]];
const money = (n) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const initials = (text) => text.split(" ").map(x=>x[0]).slice(0,2).join("");

export default function DashboardWelcome(){
  const router=useRouter(); const [user,setUser]=useState(null); const [tab,setTab]=useState("overview"); const [query,setQuery]=useState("");
  const [tasks,setTasks]=useState(initialTasks); const [activityFilter,setActivityFilter]=useState("All"); const [selected,setSelected]=useState(null); const [toast,setToast]=useState("");
  useEffect(()=>{const session=localStorage.getItem("clario-session");if(!session)router.replace("/signin");else setUser(JSON.parse(session));const saved=localStorage.getItem("clario-tasks");if(saved)setTasks(JSON.parse(saved))},[router]);
  useEffect(()=>{if(user)localStorage.setItem("clario-tasks",JSON.stringify(tasks))},[tasks,user]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(id)}},[toast]);
  const pipeline=deals.reduce((s,d)=>s+d.amount,0), contracted=deals.filter(d=>d.stage==="Contract sent").reduce((s,d)=>s+d.amount,0);
  const search=(items,fn)=>items.filter(x=>fn(x).toLowerCase().includes(query.toLowerCase()));
  const changeTab=(id)=>{setTab(id);setSelected(null);setQuery("")};
  const toggleTask=(id)=>setTasks(v=>v.map(x=>x.id===id?{...x,status:x.status==="Completed"?"In Progress":"Completed"}:x));
  const create=()=>{if(tab==="tasks")setTasks(v=>[...v,{id:Date.now(),dealId:1234567,title:"New follow-up task",notes:"Review and update this task.",priority:"Medium",status:"In Progress",type:"Task",due:"Today"}]);setToast(tab==="tasks"?"Task created":"Create form opened for this section")};
  if(!user)return <main className="crm-loading">Loading CRM…</main>;
  return <div className="nexa-app"><aside className="nexa-side"><button className="nexa-logo" onClick={()=>changeTab("overview")}><Image src="/logo.png" alt="Clario" width={105} height={62}/></button><small>WORKSPACE</small><nav>{nav.slice(0,4).map(([id,icon])=><Nav key={id} id={id} icon={icon} tab={tab} go={changeTab}/>)}</nav><small>ACTIVITY</small><nav>{nav.slice(4,6).map(([id,icon])=><Nav key={id} id={id} icon={icon} tab={tab} go={changeTab}/>)}</nav><small>INSIGHTS</small><nav><Nav id="analytics" icon="▥" tab={tab} go={changeTab}/></nav><div className="nexa-side-foot"><button>⚙ Settings</button><div><span>{user.name[0]}</span><p><b>{user.name}</b><small>{user.company}</small></p></div></div></aside>
  <section className="nexa-work"><header className="nexa-top"><b>{tab[0].toUpperCase()+tab.slice(1)}</b><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything…"/><kbd>⌘ K</kbd></label><div><button>♧</button><button className="create" onClick={create}>＋ Create</button><button className="avatar">{user.name[0]}</button></div></header>
  <main className="nexa-main">{selected?<RecordDetail record={selected} back={()=>setSelected(null)}/>:<>{tab==="overview"&&<Overview user={user} pipeline={pipeline} contracted={contracted} tasks={tasks} go={changeTab}/>} {tab==="companies"&&<Companies data={search(companies,x=>Object.values(x).join(" "))} select={setSelected}/>} {tab==="contacts"&&<Contacts data={search(contacts,x=>Object.values(x).join(" "))} select={setSelected}/>} {tab==="deals"&&<Deals data={search(deals,x=>Object.values(x).join(" "))} select={setSelected}/>} {tab==="tasks"&&<Tasks data={search(tasks,x=>Object.values(x).join(" "))} toggle={toggleTask}/>} {tab==="activity"&&<Activity filter={activityFilter} setFilter={setActivityFilter}/>} {tab==="analytics"&&<Analytics pipeline={pipeline} tasks={tasks}/>}</>}</main></section>{toast&&<div className="crm-toast">✓ {toast}</div>}</div>;
}
function Nav({id,icon,tab,go}){return <button className={tab===id?"active":""} onClick={()=>go(id)}><span>{icon}</span>{id[0].toUpperCase()+id.slice(1)}</button>}
function Hero({kicker,title,description,action}){return <div className="page-hero"><div><small>{kicker}</small><h1>{title}</h1><p>{description}</p></div>{action&&<button onClick={action}>＋ {action.name.replaceAll("_"," ")}</button>}</div>}
function Overview({user,pipeline,contracted,tasks,go}){const stats=[["Total pipeline",money(pipeline),"Across all active source stages"],["Contract sent",money(contracted),"Late-stage value, not won revenue"],["Active deals",deals.length,`${companies.length} connected companies`],["Open tasks",tasks.filter(x=>x.status!=="Completed").length,`${tasks.filter(x=>x.status==="Completed").length} completed`]];return <><Hero title={`Good morning, ${user.name.split(" ")[0]} ✦`} description="Here’s what’s happening across your customer relationships."/><div className="metric-grid">{stats.map(x=><article key={x[0]}><span>{x[0]}<i>▥</i></span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</div><div className="overview-panels"><Panel title="Sales pipeline" sub="Deal volume and value by source stage"><Pipeline/></Panel><Panel title="Pipeline trend" sub="Value by latest activity month"><Trend/></Panel><Panel title="Recent activity" sub="Latest connected touchpoints"><CompactActivity/></Panel><Panel title="Top companies" sub="Ranked by connected pipeline"><TopCompanies go={go}/></Panel></div></>}
function Companies({data,select}){return <><Hero kicker="Relationships" title="Company directory" description="Explore every organization and its commercial context." action={function Add_company(){}}/><div className="directory-tools"><label>⌕ Search companies…</label><select><option>All industries</option></select><span>{data.length} companies</span></div><div className="company-grid">{data.map(c=>{const related=deals.filter(d=>d.domain===c.domain),people=contacts.filter(x=>x.domain===c.domain);return <article key={c.id} onClick={()=>select({...c,type:"Company"})}><header><b>{initials(c.name)}</b><em>Active</em></header><h2>{c.name}</h2><p>{c.industry} · {c.city}</p><hr/><div><span>Pipeline<strong>{money(related.reduce((s,d)=>s+d.amount,0))}</strong></span><span>Deals<strong>{related.length}</strong></span><span>People<strong>{people.length}</strong></span></div><button>Open company ↗</button></article>})}</div></>}
function Contacts({data,select}){return <><Hero kicker="Relationships" title="People directory" description="Understand the people behind every customer relationship." action={function Add_contact(){}}/><div className="directory-tools"><label>⌕ Search people, roles, or companies…</label><span>{data.length} contacts</span></div><section className="people-list">{data.map(c=>{const record={...c,name:`${c.first} ${c.last}`,type:"Contact"};return <article key={c.id} onClick={()=>select(record)}><b>{c.first[0]}{c.last[0]}</b><p><strong>{c.first} {c.last}</strong><small>{c.role}</small></p><p><strong>{c.company}</strong><small>{c.email}</small></p><button onClick={event=>{event.stopPropagation();select(record)}}>✉ Email</button><i>↗</i></article>})}</section></>}
function Deals({data,select}){const stages=["Appointment scheduled","Qualified to buy","Contract sent"];return <><Hero kicker="Revenue" title="Sales pipeline" description="Track opportunities through the source-supported deal stages." action={function Add_deal(){}}/><div className="directory-tools"><label>⌕ Search deals…</label><select><option>All stages</option></select><span>{data.length} deals · {money(data.reduce((s,d)=>s+d.amount,0))}</span></div><div className="pipeline-board">{stages.map(stage=>{const rows=data.filter(d=>d.stage===stage);return <section key={stage}><header><h3>{stage}</h3><b>{rows.length}</b><small>{money(rows.reduce((s,d)=>s+d.amount,0))} pipeline</small></header>{rows.map(d=><article key={d.id} onClick={()=>select({...d,type:"Deal"})}><h4>{d.name}</h4><p>{d.company}</p><strong>{money(d.amount)}</strong><small>{d.close}</small></article>)}</section>})}</div></>}
function Tasks({data,toggle}){return <><Hero kicker="Personal workspace" title="My work" description="Turn relationship intent into the next useful action." action={function Add_task(){}}/><div className="view-tabs"><b>All tasks</b><span>Today</span><span>Open</span><span>Overdue</span><span>Completed</span></div><div className="task-metrics"><Stat label="Due today" value={data.filter(x=>x.due==="Today").length}/><Stat label="Open" value={data.filter(x=>x.status!=="Completed").length}/><Stat label="Completed" value={data.filter(x=>x.status==="Completed").length}/></div><section className="task-list">{data.map(t=>{const deal=deals.find(d=>d.id===t.dealId);return <article className={t.status==="Completed"?"done":""} key={t.id}><button onClick={()=>toggle(t.id)}>{t.status==="Completed"?"✓":""}</button><strong>{t.title}</strong><span>{deal?.company} · {deal?.name}</span><em>{t.priority}</em><small>{t.due}</small><i>↗</i></article>})}</section></>}
function Activity({filter,setFilter}){const items=[...notes.map(x=>({type:"Note",title:"Note added",meta:x.body,company:x.company,date:x.date})),...emails.map(x=>{const c=contacts.find(c=>c.id===x.contactId);return {type:"Email",title:x.subject,meta:`${x.status} · ${c?.first} ${c?.last}`,company:c?.company,date:"Recent"}}),...calls.map(x=>({type:"Call",title:x.title,meta:`${x.status} · ${x.contact}`,company:x.contact,date:x.date})),...initialTasks.map(x=>{const d=deals.find(d=>d.id===x.dealId);return {type:"Task",title:x.title,meta:`${x.status} · ${d?.name}`,company:d?.company,date:x.due}})];const shown=filter==="All"?items:items.filter(x=>x.type===filter);return <><Hero kicker="Relationships" title="Relationship timeline" description="Everything happening across your connected customer records."/><div className="view-tabs">{["All","Note","Email","Call","Task"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><section className="timeline">{shown.map((x,i)=><article key={`${x.type}-${i}`}><b>{x.type[0]}</b><time>{x.date}</time><p><strong>{x.title}</strong><small>{x.meta}</small></p><a>{x.company} ↗</a></article>)}</section></>}
function Analytics({pipeline,tasks}){return <><Hero kicker="Insights" title="Revenue patterns" description="Explore pipeline distribution across stages and companies."/><div className="metric-grid"><Stat label="Pipeline" value={money(pipeline)}/><Stat label="Average deal" value={money(pipeline/deals.length)}/><Stat label="Companies" value={companies.length}/><Stat label="Open tasks" value={tasks.filter(x=>x.status!=="Completed").length}/></div><div className="analytics-panels"><Panel title="Pipeline by stage" sub="Source stage distribution"><Pipeline/></Panel><Panel title="Top company pipeline" sub="Connected opportunity value"><TopBars/></Panel></div></>}
function Stat({label,value}){return <article><span>{label}<i>◎</i></span><strong>{value}</strong><small>Connected CRM records</small></article>}
function Panel({title,sub,children}){return <section className="data-panel"><h2>{title}</h2><p>{sub}</p>{children}</section>}
function Pipeline(){return <div className="pipeline-lines">{["Appointment scheduled","Qualified to buy","Contract sent"].map((s,i)=>{const rows=deals.filter(d=>d.stage===s),v=rows.reduce((a,d)=>a+d.amount,0);return <div key={s}><p><b>{s}</b><small>{rows.length} deals</small></p><span><i style={{width:`${v/12}%`}}/></span><strong>{money(v)}</strong></div>})}</div>}
function Trend(){return <div className="trend">{[58,84,58,84,56].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><small>{["May","Jun","Jul","Aug","Sep"][i]}</small></div>)}</div>}
function CompactActivity(){return <div className="compact-activity">{initialTasks.slice(0,5).map((task)=>{const deal=deals.find(item=>item.id===task.dealId);const company=deal?companies.find(item=>item.id===deal.companyId):null;return <div key={task.id}><b>T</b><p><strong>{task.title}</strong><small>{company?.name ?? "Unlinked company"} · {task.status}</small></p><span>↗</span></div>})}</div>}
function TopCompanies({go}){const ranked=companies.map(company=>({...company,total:deals.filter(deal=>deal.companyId===company.id).reduce((sum,deal)=>sum+deal.amount,0)})).sort((a,b)=>b.total-a.total).slice(0,5);return <div className="top-companies">{ranked.map((company,index)=><button key={company.id} onClick={()=>go("companies")}><i>{index+1}</i><b>{initials(company.name)}</b><p><strong>{company.name}</strong><small>{company.industry}</small></p><span>{money(company.total)}</span></button>)}</div>}
function TopBars(){return <div className="top-bars">{companies.map(c=>{const v=deals.find(d=>d.domain===c.domain)?.amount||0;return <div key={c.id}><span>{c.name}</span><i><b style={{width:`${v/12}%`}}/></i><strong>{money(v)}</strong></div>})}</div>}
function RecordDetail({record,back}){if(record.type==="Contact")return <ContactDetail contact={record} back={back}/>;return <><button className="back" onClick={back}>← Back to directory</button><Hero kicker={record.type} title={record.name} description={record.domain||record.email||record.company}/><div className="record-detail"><section className="data-panel"><h2>Record information</h2>{Object.entries(record).filter(([k])=>!["id","type","name"].includes(k)).map(([k,v])=><p key={k}><span>{k}</span><strong>{typeof v==="number"&&k==="amount"?money(v):v}</strong></p>)}</section><Panel title="Connected activity" sub="Linked through the imported relationship keys"><CompactActivity/></Panel></div></>}

function ContactDetail({contact,back}){const [section,setSection]=useState("Overview");const company=companies.find(item=>item.id===contact.companyId);const relatedDeals=deals.filter(item=>item.companyId===contact.companyId);const relatedEmails=emails.filter(item=>item.contactId===contact.id);const relatedCalls=calls.filter(item=>item.contactId===contact.id);const dealIds=new Set(relatedDeals.map(item=>item.id));const relatedTasks=initialTasks.filter(item=>dealIds.has(item.dealId));const sections=["Overview","Deals","Emails","Calls","Tasks","Activity"];return <div className="contact-360"><button className="back" onClick={back}>← Contacts</button><header className="contact-profile"><span>{contact.first[0]}{contact.last[0]}</span><div><small>Contact</small><h1>{contact.name}</h1><p>{contact.role} · {company?.name}</p></div><div className="contact-actions"><a href={`tel:${contact.phone}`}>☎ Call</a><a className="primary" href={`mailto:${contact.email}`}>✉ Email</a></div></header><nav className="contact-tabs">{sections.map(item=><button className={section===item?"active":""} onClick={()=>setSection(item)} key={item}>{item}</button>)}</nav>{section==="Overview"&&<div className="contact-overview"><section className="data-panel contact-info"><h2>Contact information</h2><Info icon="✉" label="Work email" value={contact.email}/><Info icon="☎" label="Phone" value={contact.phone}/><Info icon="▥" label="Company" value={company?.name||"Unlinked"}/></section><section className="data-panel related-deals"><h2>Related deals</h2><p>Opportunities at {company?.name}</p>{relatedDeals.map(deal=><article key={deal.id}><div><strong>{deal.name}</strong><small>{deal.stage}</small></div><b>{money(deal.amount)}</b></article>)}</section></div>}{section==="Deals"&&<DetailList title="Related deals" rows={relatedDeals.map(x=>[x.name,x.stage,money(x.amount)])}/>} {section==="Emails"&&<DetailList title="Recent emails" rows={relatedEmails.map(x=>[x.subject,`${x.direction} · ${x.body}`,x.status])}/>} {section==="Calls"&&<DetailList title="Recent calls" rows={relatedCalls.map(x=>[x.title,`${x.direction} · ${x.notes}`,x.status])}/>} {section==="Tasks"&&<DetailList title="Related tasks" rows={relatedTasks.map(x=>[x.title,x.notes,x.status])}/>} {section==="Activity"&&<DetailList title="Contact activity" rows={[...relatedEmails.map(x=>[x.subject,"Email",x.status]),...relatedCalls.map(x=>[x.title,"Call",x.status])]}/>} {section==="Overview"&&<DetailList title="Recent emails" rows={relatedEmails.slice(0,4).map(x=>[x.subject,`${x.direction} · ${x.body}`,x.status])}/>}</div>}
function Info({icon,label,value}){return <div className="info-row"><i>{icon}</i><p><small>{label}</small><strong>{value}</strong></p></div>}
function DetailList({title,rows}){return <section className="data-panel contact-detail-list"><h2>{title}</h2><p>Communication connected by canonical contact ID</p>{rows.length?rows.map((row,index)=><article key={`${row[0]}-${index}`}><b>{row[0][0]}</b><div><strong>{row[0]}</strong><small>{row[1]}</small></div><span>{row[2]}</span></article>):<div className="empty-related">No connected records for this contact.</div>}</section>}
