"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { companies, contacts, deals, notes, emails, calls, initialTasks } from "@/data/seed";
import OverviewCommandCenter from "@/components/dashboard/OverviewCommandCenter";
import CompaniesWorkspace from "@/components/companies/CompaniesWorkspace";
import ContactsWorkspace from "@/components/contacts/ContactsWorkspace";
import ContactWorkspace from "@/components/contacts/ContactWorkspace";
import AnalyticsWorkspace from "@/components/AnalyticsWorkspace";
import TasksWorkspace from "@/components/TasksWorkspace";
import ActivityWorkspace from "@/components/ActivityWorkspace";

const nav = [["overview","⌂"],["companies","▥"],["contacts","▣"],["deals","▱"],["tasks","☑"],["activity","◉"],["analytics","▥"]];
const money = (n) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const initials = (text) => text.split(" ").map(x=>x[0]).slice(0,2).join("");

export default function DashboardWelcome(){
  const router=useRouter(); const [user,setUser]=useState(null); const [tab,setTab]=useState("overview"); const [query,setQuery]=useState(""); const [createOpen,setCreateOpen]=useState(false);
  const [companyRecords,setCompanyRecords]=useState(companies);
  const [contactRecords,setContactRecords]=useState(contacts);
  const [tasks,setTasks]=useState(initialTasks); const [activityFilter,setActivityFilter]=useState("All"); const [selected,setSelected]=useState(null); const [toast,setToast]=useState("");
  useEffect(()=>{const session=localStorage.getItem("clario-session");if(!session)router.replace("/signin");else setUser(JSON.parse(session));const saved=localStorage.getItem("clario-tasks");if(saved)setTasks(JSON.parse(saved));const savedCompanies=localStorage.getItem("clario-companies");if(savedCompanies)setCompanyRecords(JSON.parse(savedCompanies));const savedContacts=localStorage.getItem("clario-contacts");if(savedContacts)setContactRecords(JSON.parse(savedContacts))},[router]);
  useEffect(()=>{if(user)localStorage.setItem("clario-tasks",JSON.stringify(tasks))},[tasks,user]);
  useEffect(()=>{if(user)localStorage.setItem("clario-companies",JSON.stringify(companyRecords))},[companyRecords,user]);
  useEffect(()=>{if(user)localStorage.setItem("clario-contacts",JSON.stringify(contactRecords))},[contactRecords,user]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(id)}},[toast]);
  useEffect(()=>{const onKey=(event)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();document.querySelector(".global-search input")?.focus()}if(event.key==="Escape"){setQuery("");setCreateOpen(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
  const pipeline=deals.reduce((s,d)=>s+d.amount,0), contracted=deals.filter(d=>d.stage==="Contract sent").reduce((s,d)=>s+d.amount,0);
  const search=(items,fn)=>items.filter(x=>fn(x).toLowerCase().includes(query.toLowerCase()));
  const changeTab=(id,context="")=>{setTab(id);setSelected(null);setQuery(context)};
  const searchResults=useMemo(()=>{if(query.trim().length<2)return[];const q=query.toLowerCase();return [
    ...companyRecords.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q)).slice(0,3).map(x=>({kind:"Company",label:x.name,meta:x.industry,record:{...x,type:"Company"}})),
    ...contactRecords.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q)).slice(0,3).map(x=>({kind:"Contact",label:x.name,meta:x.company,record:{...x,type:"Contact"}})),
    ...deals.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q)).slice(0,3).map(x=>({kind:"Deal",label:x.name,meta:x.company,record:{...x,type:"Deal"}})),
    ...tasks.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q)).slice(0,3).map(x=>({kind:"Task",label:x.title,meta:x.status,tab:"tasks"}))
  ].slice(0,8)},[query,tasks,companyRecords,contactRecords]);
  const addCompany=async(values)=>{await new Promise(resolve=>setTimeout(resolve,450));const company={...values,id:`company_ui_${Date.now()}`,createdAt:new Date().toISOString(),sourceType:"clarion-ui"};setCompanyRecords(current=>[company,...current]);return company};
  const addContact=async(values)=>{await new Promise(resolve=>setTimeout(resolve,450));const contact={...values,id:`contact_ui_${Date.now()}`,createdAt:new Date().toISOString()};setContactRecords(current=>[contact,...current]);return contact};
  const toggleTask=(id)=>setTasks(v=>v.map(x=>x.id===id?{...x,status:x.status==="Completed"?"In Progress":"Completed"}:x));
  const create=()=>{if(tab==="tasks")setTasks(v=>[...v,{id:Date.now(),dealId:1234567,title:"New follow-up task",notes:"Review and update this task.",priority:"Medium",status:"In Progress",type:"Task",due:"Today"}]);setToast(tab==="tasks"?"Task created":"Create form opened for this section")};
  if(!user)return <main className="crm-loading">Loading CRM…</main>;
  return <div className="nexa-app"><aside className="nexa-side"><button className="nexa-logo" onClick={()=>changeTab("overview")}><Image src="/logo.png" alt="Clario" width={105} height={62}/></button><small>WORKSPACE</small><nav>{nav.slice(0,4).map(([id,icon])=><Nav key={id} id={id} icon={icon} tab={tab} go={changeTab}/>)}</nav><small>ACTIVITY</small><nav>{nav.slice(4,6).map(([id,icon])=><Nav key={id} id={id} icon={icon} tab={tab} go={changeTab}/>)}</nav><small>INSIGHTS</small><nav><Nav id="analytics" icon="▥" tab={tab} go={changeTab}/></nav><div className="nexa-side-foot"><button>⚙ Settings</button><div><span>{user.name[0]}</span><p><b>{user.name}</b><small>{user.company}</small></p></div></div></aside>
  <section className="nexa-work"><header className="nexa-top"><b>{tab[0].toUpperCase()+tab.slice(1)}</b><label className="global-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything…"/><kbd>⌘ K</kbd>{searchResults.length>0&&<div className="search-results" role="listbox">{searchResults.map((result,index)=><button key={`${result.kind}-${result.label}-${index}`} onClick={()=>{if(result.record){setSelected(result.record);setQuery("")}else changeTab(result.tab,result.label)}}><b>{result.kind}</b><span><strong>{result.label}</strong><small>{result.meta}</small></span><i>→</i></button>)}</div>}</label><div><button aria-label="Notifications">♧</button><span className="create-wrap"><button className="create" onClick={()=>setCreateOpen(value=>!value)} aria-expanded={createOpen}>＋ Create</button>{createOpen&&<div className="create-menu"><b>Create new</b>{[["Company","companies"],["Contact","contacts"],["Deal","deals"],["Task","tasks"],["Note","activity"]].map(([label,destination])=><button key={label} onClick={()=>{setCreateOpen(false);changeTab(destination);setToast(`${label} workspace opened`)}}>{label}<span>→</span></button>)}</div>}</span><button className="avatar">{user.name[0]}</button></div></header>
  <main className="nexa-main">{selected?<RecordDetail record={selected} contactsData={contactRecords} companiesData={companyRecords} tasksData={tasks} onToggleTask={toggleTask} onSelect={setSelected} back={()=>setSelected(null)}/>:<>{tab==="overview"&&<OverviewCommandCenter user={user} tasks={tasks} companiesData={companyRecords} onNavigate={changeTab} onSelect={setSelected}/>} {tab==="companies"&&<CompaniesWorkspace companies={companyRecords} contacts={contactRecords} deals={deals} user={user} globalQuery={query} onAdd={addCompany} onSelect={setSelected}/>} {tab==="contacts"&&<ContactsWorkspace contacts={contactRecords} companies={companyRecords} user={user} globalQuery={query} onAdd={addContact} onSelect={setSelected}/>} {tab==="deals"&&<Deals data={search(deals,x=>Object.values(x).join(" "))} select={setSelected}/>} {tab==="tasks"&&<TasksWorkspace tasks={tasks} onChange={setTasks} query={query} onClearSearch={()=>setQuery("")} onToast={setToast}/>} {tab==="activity"&&<ActivityWorkspace tasks={tasks} initialType={activityFilter}/>} {tab==="analytics"&&<AnalyticsWorkspace tasks={tasks} onViewCompany={company=>setSelected({...company,type:"Company"})} onViewDeal={deal=>setSelected({...deal,type:"Deal"})}/>}</>}</main></section>{toast&&<div className="crm-toast">✓ {toast}</div>}</div>;
}
function Nav({id,icon,tab,go}){return <button className={tab===id?"active":""} onClick={()=>go(id)}><span>{icon}</span>{id[0].toUpperCase()+id.slice(1)}</button>}
function Hero({kicker,title,description,action}){return <div className="page-hero"><div><small>{kicker}</small><h1>{title}</h1><p>{description}</p></div>{action&&<button onClick={action}>＋ {action.name.replaceAll("_"," ")}</button>}</div>}
function activate(event, action){if(event.key === "Enter" || event.key === " "){event.preventDefault();action()}}
function Overview({user,pipeline,contracted,tasks,go}){const stats=[["Total pipeline",money(pipeline),"Across all active source stages","deals"],["Contract sent",money(contracted),"Late-stage value, not won revenue","deals"],["Active deals",deals.length,`${companies.length} connected companies`,`deals`],["Open tasks",tasks.filter(x=>x.status!=="Completed").length,`${tasks.filter(x=>x.status==="Completed").length} completed`,`tasks`]];return <><Hero title={`Good morning, ${user.name.split(" ")[0]} ✦`} description="Here’s what’s happening across your customer relationships."/><div className="metric-grid">{stats.map(x=><article className="overview-link-card" role="button" tabIndex={0} aria-label={`Open ${x[0]}`} onClick={()=>go(x[3])} onKeyDown={event=>activate(event,()=>go(x[3]))} key={x[0]}><span>{x[0]}<i>▥</i></span><strong>{x[1]}</strong><small>{x[2]}</small><em>View {x[3]}</em></article>)}</div><div className="overview-panels"><Panel title="Sales pipeline" sub="Deal volume and value by source stage" onClick={()=>go("deals")}><Pipeline go={go}/></Panel><Panel title="Pipeline trend" sub="Value by latest activity month" onClick={()=>go("analytics")}><Trend/></Panel><Panel title="Recent activity" sub="Latest connected touchpoints" onClick={()=>go("activity")}><CompactActivity/></Panel><Panel title="Top companies" sub="Ranked by connected pipeline" onClick={()=>go("companies")}><TopCompanies go={go}/></Panel></div></>}
function Companies({data,select}){return <><Hero kicker="Relationships" title="Company directory" description="Explore every organization and its commercial context." action={function Add_company(){}}/><div className="directory-tools"><label>⌕ Search companies…</label><select><option>All industries</option></select><span>{data.length} companies</span></div><div className="company-grid">{data.map(c=>{const related=deals.filter(d=>d.domain===c.domain),people=contacts.filter(x=>x.domain===c.domain);return <article key={c.id} onClick={()=>select({...c,type:"Company"})}><header><b>{initials(c.name)}</b><em>Active</em></header><h2>{c.name}</h2><p>{c.industry} · {c.city}</p><hr/><div><span>Pipeline<strong>{money(related.reduce((s,d)=>s+d.amount,0))}</strong></span><span>Deals<strong>{related.length}</strong></span><span>People<strong>{people.length}</strong></span></div><button>Open company ↗</button></article>})}</div></>}
function Contacts({data,select}){return <><Hero kicker="Relationships" title="People directory" description="Understand the people behind every customer relationship." action={function Add_contact(){}}/><div className="directory-tools"><label>⌕ Search people, roles, or companies…</label><span>{data.length} contacts</span></div><section className="people-list">{data.map(c=>{const record={...c,name:`${c.first} ${c.last}`,type:"Contact"};return <article key={c.id} onClick={()=>select(record)}><b>{c.first[0]}{c.last[0]}</b><p><strong>{c.first} {c.last}</strong><small>{c.role}</small></p><p><strong>{c.company}</strong><small>{c.email}</small></p><button onClick={event=>{event.stopPropagation();select(record)}}>✉ Email</button><i>↗</i></article>})}</section></>}
function Deals({data,select}){const stages=["Appointment scheduled","Qualified to buy","Contract sent"];return <><Hero kicker="Revenue" title="Sales pipeline" description="Track opportunities through the source-supported deal stages." action={function Add_deal(){}}/><div className="directory-tools"><label>⌕ Search deals…</label><select><option>All stages</option></select><span>{data.length} deals · {money(data.reduce((s,d)=>s+d.amount,0))}</span></div><div className="pipeline-board">{stages.map(stage=>{const rows=data.filter(d=>d.stage===stage);return <section key={stage}><header><h3>{stage}</h3><b>{rows.length}</b><small>{money(rows.reduce((s,d)=>s+d.amount,0))} pipeline</small></header>{rows.map(d=><article key={d.id} onClick={()=>select({...d,type:"Deal"})}><h4>{d.name}</h4><p>{d.company}</p><strong>{money(d.amount)}</strong><small>{d.close}</small></article>)}</section>})}</div></>}
function Tasks({data,toggle}){return <><Hero kicker="Personal workspace" title="My work" description="Turn relationship intent into the next useful action." action={function Add_task(){}}/><div className="view-tabs"><b>All tasks</b><span>Today</span><span>Open</span><span>Overdue</span><span>Completed</span></div><div className="task-metrics"><Stat label="Due today" value={data.filter(x=>x.due==="Today").length}/><Stat label="Open" value={data.filter(x=>x.status!=="Completed").length}/><Stat label="Completed" value={data.filter(x=>x.status==="Completed").length}/></div><section className="task-list">{data.map(t=>{const deal=deals.find(d=>d.id===t.dealId);return <article className={t.status==="Completed"?"done":""} key={t.id}><button onClick={()=>toggle(t.id)}>{t.status==="Completed"?"✓":""}</button><strong>{t.title}</strong><span>{deal?.company} · {deal?.name}</span><em>{t.priority}</em><small>{t.due}</small><i>↗</i></article>})}</section></>}
function Activity({filter,setFilter}){const items=[...notes.map(x=>({type:"Note",title:"Note added",meta:x.body,company:x.company,date:x.date})),...emails.map(x=>{const c=contacts.find(c=>c.id===x.contactId);return {type:"Email",title:x.subject,meta:`${x.status} · ${c?.first} ${c?.last}`,company:c?.company,date:"Recent"}}),...calls.map(x=>({type:"Call",title:x.title,meta:`${x.status} · ${x.contact}`,company:x.contact,date:x.date})),...initialTasks.map(x=>{const d=deals.find(d=>d.id===x.dealId);return {type:"Task",title:x.title,meta:`${x.status} · ${d?.name}`,company:d?.company,date:x.due}})];const shown=filter==="All"?items:items.filter(x=>x.type===filter);return <><Hero kicker="Relationships" title="Relationship timeline" description="Everything happening across your connected customer records."/><div className="view-tabs">{["All","Note","Email","Call","Task"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><section className="timeline">{shown.map((x,i)=><article key={`${x.type}-${i}`}><b>{x.type[0]}</b><time>{x.date}</time><p><strong>{x.title}</strong><small>{x.meta}</small></p><a>{x.company} ↗</a></article>)}</section></>}
function Analytics({pipeline,tasks}){return <><Hero kicker="Insights" title="Revenue patterns" description="Explore pipeline distribution across stages and companies."/><div className="metric-grid"><Stat label="Pipeline" value={money(pipeline)}/><Stat label="Average deal" value={money(pipeline/deals.length)}/><Stat label="Companies" value={companies.length}/><Stat label="Open tasks" value={tasks.filter(x=>x.status!=="Completed").length}/></div><div className="analytics-panels"><Panel title="Pipeline by stage" sub="Source stage distribution"><Pipeline/></Panel><Panel title="Top company pipeline" sub="Connected opportunity value"><TopBars/></Panel></div></>}
function Stat({label,value}){return <article><span>{label}<i>◎</i></span><strong>{value}</strong><small>Connected CRM records</small></article>}
function Panel({title,sub,children,onClick}){const props=onClick?{role:"button",tabIndex:0,onClick,onKeyDown:event=>activate(event,onClick),"aria-label":`Open ${title}`}:{ };return <section className={`data-panel${onClick?" overview-link-panel":""}`} {...props}><h2>{title}</h2><p>{sub}</p>{children}</section>}
function Pipeline({go}){const stages=["Appointment scheduled","Qualified to buy","Contract sent"],total=deals.reduce((sum,d)=>sum+d.amount,0),max=Math.max(...stages.map(s=>deals.filter(d=>d.stage===s).reduce((sum,d)=>sum+d.amount,0)));return <div className="pipeline-lines">{stages.map(s=>{const rows=deals.filter(d=>d.stage===s),value=rows.reduce((sum,d)=>sum+d.amount,0),percentage=total?((value/total)*100).toFixed(1):0;return <button className="pipeline-stage-link" key={s} onClick={event=>{event.stopPropagation();go?.("deals")}} aria-label={`${s}, ${rows.length} deals, ${money(value)} pipeline value`}><p><b>{s}</b><small>{rows.length} deals · {percentage}% of pipeline</small></p><span><i style={{width:`${max?(value/max)*100:0}%`}}/></span><strong>{money(value)}</strong><em className="data-tooltip"><b>{s}</b><small>{rows.length} deals · {money(value)} pipeline value</small><small>{percentage}% of total · Average {money(rows.length?value/rows.length:0)}</small></em></button>})}</div>}
function Trend(){return <div className="trend">{[58,84,58,84,56].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><small>{["May","Jun","Jul","Aug","Sep"][i]}</small></div>)}</div>}
function CompactActivity(){return <div className="compact-activity">{initialTasks.slice(0,5).map((task)=>{const deal=deals.find(item=>item.id===task.dealId);const company=deal?companies.find(item=>item.id===deal.companyId):null;return <div key={task.id}><b>T</b><p><strong>{task.title}</strong><small>{company?.name ?? "Unlinked company"} · {task.status}</small></p><span>↗</span></div>})}</div>}
function TopCompanies({go}){const ranked=companies.map(company=>({...company,total:deals.filter(deal=>deal.companyId===company.id).reduce((sum,deal)=>sum+deal.amount,0)})).sort((a,b)=>b.total-a.total).slice(0,5);return <div className="top-companies">{ranked.map((company,index)=><button key={company.id} onClick={()=>go("companies")}><i>{index+1}</i><b>{initials(company.name)}</b><p><strong>{company.name}</strong><small>{company.industry}</small></p><span>{money(company.total)}</span></button>)}</div>}
function TopBars(){return <div className="top-bars">{companies.map(c=>{const v=deals.find(d=>d.domain===c.domain)?.amount||0;return <div key={c.id}><span>{c.name}</span><i><b style={{width:`${v/12}%`}}/></i><strong>{money(v)}</strong></div>})}</div>}
function RecordDetail({record,back,contactsData=contacts,companiesData=companies,tasksData=initialTasks,onToggleTask=()=>{},onSelect=()=>{}}){if(record.type==="Contact")return <ContactWorkspace contact={record} companies={companiesData} deals={deals} emails={emails} calls={calls} tasks={tasksData} notes={notes} onBack={back} onToggleTask={onToggleTask} onSelectCompany={company=>onSelect({...company,type:"Company"})}/>;if(record.type==="Company")return <CompanyDetail company={record} contactsData={contactsData} back={back}/>;return <><button className="back" onClick={back}>← Back to directory</button><Hero kicker={record.type} title={record.name} description={record.domain||record.email||record.company}/><div className="record-detail"><section className="data-panel"><h2>Record information</h2>{Object.entries(record).filter(([k])=>!["id","type","name"].includes(k)).map(([k,v])=><p key={k}><span>{k}</span><strong>{typeof v==="number"&&k==="amount"?money(v):v}</strong></p>)}</section><Panel title="Connected activity" sub="Linked through the imported relationship keys"><CompactActivity/></Panel></div></>}

function CompanyDetail({company,back,contactsData=contacts}){const relatedContacts=contactsData.filter(item=>item.companyId===company.id),relatedDeals=deals.filter(item=>item.companyId===company.id),relatedNotes=notes.filter(item=>item.companyId===company.id);const fields=[["Website",company.website||company.domain],["Phone",company.phone],["Email",company.email],["Industry",company.industry],["Location",[company.city,company.state,company.country].filter(Boolean).join(", ")],["Company size",company.companySize],["Lifecycle",company.lifecycleStatus],["Source",company.source],["Annual revenue",company.annualRevenue?money(company.annualRevenue):null],["Notes",company.notes]];return <div className="company-360"><button className="back" onClick={back}>← Companies</button><header className="company-profile"><b>{initials(company.name)}</b><div><small>{company.sourceType==="clarion-ui"?"Clarion company":"Company"}</small><h1>{company.name}</h1><p>{company.domain||company.industry||"New customer relationship"}</p></div></header><div className="company-360-grid"><section className="data-panel"><h2>Company information</h2>{fields.filter(([,value])=>value).map(([label,value])=><p key={label}><span>{label}</span><strong>{value}</strong></p>)}</section><section className="data-panel company-relationship-summary"><h2>Relationship overview</h2><div><span>Contacts<strong>{relatedContacts.length}</strong></span><span>Deals<strong>{relatedDeals.length}</strong></span><span>Pipeline<strong>{money(relatedDeals.reduce((sum,deal)=>sum+deal.amount,0))}</strong></span></div>{!relatedContacts.length&&<article><b>No contacts yet</b><p>Contacts will appear as people are connected to this company.</p></article>}{!relatedDeals.length&&<article><b>No deals yet</b><p>Create an opportunity when this relationship enters the pipeline.</p></article>}{!relatedNotes.length&&<article><b>No activity yet</b><p>Activity will appear here as the relationship develops.</p></article>}</section></div></div>}

function ContactDetail({contact,back,companiesData=companies}){const [section,setSection]=useState("Overview");const company=companiesData.find(item=>item.id===contact.companyId)||{name:contact.company,domain:contact.domain};const relatedDeals=deals.filter(item=>item.companyId===contact.companyId);const relatedEmails=emails.filter(item=>item.contactId===contact.id);const relatedCalls=calls.filter(item=>item.contactId===contact.id);const dealIds=new Set(relatedDeals.map(item=>item.id));const relatedTasks=initialTasks.filter(item=>dealIds.has(item.dealId));const sections=["Overview","Deals","Emails","Calls","Tasks","Activity"];return <div className="contact-360"><button className="back" onClick={back}>← Contacts</button><header className="contact-profile"><span>{contact.first[0]}{contact.last[0]}</span><div><small>Contact</small><h1>{contact.name}</h1><p>{contact.role} · {company?.name}</p></div><div className="contact-actions"><a href={`tel:${contact.phone}`}>☎ Call</a><a className="primary" href={`mailto:${contact.email}`}>✉ Email</a></div></header><nav className="contact-tabs">{sections.map(item=><button className={section===item?"active":""} onClick={()=>setSection(item)} key={item}>{item}</button>)}</nav>{section==="Overview"&&<div className="contact-overview"><section className="data-panel contact-info"><h2>Contact information</h2><Info icon="✉" label="Work email" value={contact.email}/><Info icon="☎" label="Phone" value={contact.phone}/><Info icon="▥" label="Company" value={company?.name||"Unlinked"}/></section><section className="data-panel related-deals"><h2>Related deals</h2><p>Opportunities at {company?.name}</p>{relatedDeals.map(deal=><article key={deal.id}><div><strong>{deal.name}</strong><small>{deal.stage}</small></div><b>{money(deal.amount)}</b></article>)}</section></div>}{section==="Deals"&&<DetailList title="Related deals" rows={relatedDeals.map(x=>[x.name,x.stage,money(x.amount)])}/>} {section==="Emails"&&<DetailList title="Recent emails" rows={relatedEmails.map(x=>[x.subject,`${x.direction} · ${x.body}`,x.status])}/>} {section==="Calls"&&<DetailList title="Recent calls" rows={relatedCalls.map(x=>[x.title,`${x.direction} · ${x.notes}`,x.status])}/>} {section==="Tasks"&&<DetailList title="Related tasks" rows={relatedTasks.map(x=>[x.title,x.notes,x.status])}/>} {section==="Activity"&&<DetailList title="Contact activity" rows={[...relatedEmails.map(x=>[x.subject,"Email",x.status]),...relatedCalls.map(x=>[x.title,"Call",x.status])]}/>} {section==="Overview"&&<DetailList title="Recent emails" rows={relatedEmails.slice(0,4).map(x=>[x.subject,`${x.direction} · ${x.body}`,x.status])}/>}</div>}
function Info({icon,label,value}){return <div className="info-row"><i>{icon}</i><p><small>{label}</small><strong>{value}</strong></p></div>}
function DetailList({title,rows}){return <section className="data-panel contact-detail-list"><h2>{title}</h2><p>Communication connected by canonical contact ID</p>{rows.length?rows.map((row,index)=><article key={`${row[0]}-${index}`}><b>{row[0][0]}</b><div><strong>{row[0]}</strong><small>{row[1]}</small></div><span>{row[2]}</span></article>):<div className="empty-related">No connected records for this contact.</div>}</section>}
