"use client";

import { useMemo, useState } from "react";

const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
const date=value=>value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(`${value}T12:00:00`)):"No date";
const avatar=c=>`${c.first?.[0]||c.name?.[0]||"?"}${c.last?.[0]||c.name?.split(" ")[1]?.[0]||""}`;

function Empty({icon,title,text}){return <div className="cx-empty"><span>{icon}</span><strong>{title}</strong><p>{text}</p></div>}
function Card({title,sub,children,wide=false}){return <section className={`cx-card ${wide?"cx-wide-card":""}`}><header><div><h2>{title}</h2><p>{sub}</p></div></header>{children}</section>}
function Row({icon,title,meta,value,onClick,task,onToggle}){const body=<><i>{icon}</i><span><strong>{title}</strong><small>{meta}</small></span>{value&&<em>{value}</em>}<b>→</b></>;return task?<div className={`cx-row cx-task-row ${task.status==="Completed"?"done":""}`}><button className="cx-check" onClick={()=>onToggle(task.id)} aria-label={`Toggle ${title}`}>{task.status==="Completed"?"✓":""}</button><button onClick={onClick}>{body}</button></div>:<button className="cx-row" onClick={onClick}>{body}</button>}

function Drawer({item,onClose,onToggle}){if(!item)return null;const fields=item.kind==="Deal"?[["Stage",item.stage],["Value",money(item.amount)],["Expected close",date(item.close)],["Company",item.company]]:item.kind==="Email"?[["Direction",item.direction],["Status",item.status],["Date",date(item.date)]]:item.kind==="Call"?[["Direction",item.direction],["Status",item.status],["Source",item.source],["Date",date(item.date)]]:[["Status",item.status],["Priority",item.priority],["Type",item.type],["Due",date(item.due)]];return <div className="cx-drawer-layer" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="cx-drawer" role="dialog" aria-modal="true"><header><span>{item.kind}</span><button onClick={onClose} aria-label="Close">×</button></header><h2>{item.name||item.subject||item.title}</h2><div className="cx-drawer-fields">{fields.filter(([,v])=>v).map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>{(item.body||item.notes)&&<div className="cx-message"><small>{item.kind==="Email"?"Message":"Notes"}</small><p>{item.body||item.notes}</p></div>}{item.kind==="Task"&&<button className="cx-drawer-action" onClick={()=>onToggle(item.id)}>{item.status==="Completed"?"Reopen task":"Mark complete"}</button>}</aside></div>}

function Header({contact,company,onBack,onCompany}){const[menu,setMenu]=useState(false);return <><button className="cx-back" onClick={onBack}>← Back to contacts</button><header className="cx-profile"><span className="cx-avatar">{avatar(contact)}</span><div className="cx-identity"><small>Contact record</small><h1>{contact.name}</h1><p>{contact.role||"Contact"}{company?.name&&<> at <button onClick={onCompany}>{company.name}</button></>}</p><div><a href={`mailto:${contact.email}`}>✉ {contact.email}</a>{contact.phone&&<a href={`tel:${contact.phone}`}>☎ {contact.phone}</a>}</div></div><div className="cx-actions"><a href={`tel:${contact.phone}`}>☎ <span>Call</span></a><a className="primary" href={`mailto:${contact.email}`}>✉ <span>Email</span></a><div className="cx-more"><button onClick={()=>setMenu(v=>!v)} aria-label="More actions">•••</button>{menu&&<div><button onClick={()=>{setMenu(false);onCompany()}}>View company <span>→</span></button></div>}</div></div></header></>}

function Tools({query,setQuery,placeholder,children}){return <div className="cx-tools"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label>{children}</div>}
function Pills({items,value,onChange}){return <div className="cx-pills">{items.map(item=><button className={value===item?"active":""} onClick={()=>onChange(item)} key={item}>{item}</button>)}</div>}

export default function ContactWorkspace({contact,companies,deals,emails,calls,tasks,notes,onBack,onSelectCompany,onToggleTask}){
 const[tab,setTab]=useState("All"),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[detail,setDetail]=useState(null),[notice,setNotice]=useState("");
 const company=companies.find(x=>x.id===contact.companyId)||(contact.company?{name:contact.company,domain:contact.domain}:null);
 const rDeals=useMemo(()=>deals.filter(x=>x.companyId===contact.companyId),[contact.companyId,deals]);
 const dealIds=useMemo(()=>new Set(rDeals.map(x=>x.id)),[rDeals]);
 const rEmails=useMemo(()=>emails.filter(x=>x.contactId===contact.id),[contact.id,emails]);
 const rCalls=useMemo(()=>calls.filter(x=>x.contactId===contact.id),[calls,contact.id]);
 const rTasks=useMemo(()=>tasks.filter(x=>dealIds.has(x.dealId)),[dealIds,tasks]);
 const rNotes=useMemo(()=>notes.filter(x=>x.companyId===contact.companyId),[contact.companyId,notes]);
 const activity=useMemo(()=>[...rEmails.map(record=>({kind:"Email",title:record.subject,date:record.date,status:record.status,record})),...rCalls.map(record=>({kind:"Call",title:record.title,date:record.date,status:record.status,record})),...rTasks.map(record=>({kind:"Task",title:record.title,date:record.due,status:record.status,record})),...rDeals.map(record=>({kind:"Deal",title:record.name,date:record.close,status:record.stage,record})),...rNotes.map(record=>({kind:"Note",title:record.body,date:record.date,status:"Recorded",record}))].sort((a,b)=>(b.date||"").localeCompare(a.date||"")),[rCalls,rDeals,rEmails,rNotes,rTasks]);
 const tabs=[["All",activity.length],["Deals",rDeals.length],["Emails",rEmails.length],["Calls",rCalls.length],["Tasks",rTasks.length],["Activity",activity.length]];
 const open=(kind,item)=>setDetail({...item,kind:kind==="Note"?"Note":kind,title:kind==="Note"?"Relationship note":item.title});
 const toggle=id=>{const wasDone=tasks.find(x=>x.id===id)?.status==="Completed";onToggleTask(id);setDetail(current=>current?.kind==="Task"&&current.id===id?{...current,status:wasDone?"In Progress":"Completed"}:current);setNotice(wasDone?"Task reopened":"Task completed");setTimeout(()=>setNotice(""),1800)};
 const switchTab=name=>{setTab(name);setQuery("");setFilter("All")},matches=item=>Object.values(item).join(" ").toLowerCase().includes(query.toLowerCase());
 const onCompany=()=>company?.id&&onSelectCompany(company),today=new Date().toISOString().slice(0,10);
 const taskList=rTasks.filter(x=>matches(x)&&(filter==="All"||(filter==="Open"&&x.status!=="Completed")||(filter==="Completed"&&x.status==="Completed")||(filter==="Overdue"&&x.status!=="Completed"&&x.due<today)));
 const activityTypes=["All",...new Set(activity.map(x=>x.kind))],activityList=activity.filter(x=>(filter==="All"||x.kind===filter)&&matches(x));
 const pipeline=rDeals.reduce((sum,x)=>sum+x.amount,0),lastTouch=activity[0];
 return <div className="cx-workspace"><Header contact={contact} company={company} onBack={onBack} onCompany={onCompany}/><nav className="cx-tabs">{tabs.map(([name,count])=><button className={tab===name?"active":""} onClick={()=>switchTab(name)} key={name}>{name}<span>{count}</span></button>)}</nav>
 {tab==="All"&&<div className="cx-grid"><Card title="Contact information" sub="Primary profile and relationship details"><dl className="cx-info"><div><dt>Work email</dt><dd><a href={`mailto:${contact.email}`}>{contact.email}</a></dd></div>{contact.phone&&<div><dt>Phone</dt><dd><a href={`tel:${contact.phone}`}>{contact.phone}</a></dd></div>}<div><dt>Company</dt><dd><button onClick={onCompany}>{company?.name||"Unlinked"} {company&&"↗"}</button></dd></div>{contact.favorite&&<div><dt>Known preference</dt><dd>{contact.favorite}</dd></div>}</dl></Card><Card title="Relationship snapshot" sub="Live totals from connected records"><div className="cx-metrics"><div><span>Open pipeline</span><strong>{money(pipeline)}</strong></div><div><span>Related deals</span><strong>{rDeals.length}</strong></div><div><span>Open tasks</span><strong>{rTasks.filter(x=>x.status!=="Completed").length}</strong></div><div><span>Last touch</span><strong>{lastTouch?date(lastTouch.date):"None yet"}</strong></div></div></Card>
 <Card title="Recent deals" sub={`Opportunities at ${company?.name||"this contact"}`}>{rDeals.length?rDeals.slice(0,3).map(x=><Row key={x.id} icon="D" title={x.name} meta={`${x.stage} · closes ${date(x.close)}`} value={money(x.amount)} onClick={()=>open("Deal",x)}/>):<Empty icon="◇" title="No related deals" text="Company opportunities will appear here."/>}</Card><Card title="Communication" sub="Latest contact-specific emails and calls">{[...rEmails.map(x=>({...x,kind:"Email"})),...rCalls.map(x=>({...x,kind:"Call"}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(x=><Row key={`${x.kind}-${x.id}`} icon={x.kind[0]} title={x.subject||x.title} meta={`${x.direction} · ${date(x.date)}`} value={x.status} onClick={()=>open(x.kind,x)}/>)}{!rEmails.length&&!rCalls.length&&<Empty icon="✉" title="No communication yet" text="Connected emails and calls will appear here."/>}</Card>
 <Card title="Tasks" sub="Follow-ups tied to this relationship" wide>{rTasks.length?rTasks.slice(0,4).map(x=><Row key={x.id} icon="T" title={x.title} meta={`${x.priority} priority · due ${date(x.due)}`} value={x.status} task={x} onToggle={toggle} onClick={()=>open("Task",x)}/>):<Empty icon="✓" title="No connected tasks" text="Tasks linked through related deals will appear here."/>}</Card><Card title="Latest activity" sub="Every connected customer touchpoint" wide>{activity.length?activity.slice(0,5).map((x,i)=><Row key={`${x.kind}-${x.record.id}-${i}`} icon={x.kind[0]} title={x.title} meta={`${x.kind} · ${date(x.date)}`} value={x.status} onClick={()=>open(x.kind,x.record)}/>):<Empty icon="◷" title="No activity yet" text="Customer events will form this timeline."/>}</Card></div>}
 {tab==="Deals"&&<Card title="Related deals" sub={`${rDeals.length} opportunities connected through ${company?.name||"this contact"}`}><div className="cx-list">{rDeals.length?rDeals.map(x=><Row key={x.id} icon="D" title={x.name} meta={`${x.stage} · closes ${date(x.close)}`} value={money(x.amount)} onClick={()=>open("Deal",x)}/>):<Empty icon="◇" title="No related deals" text="This contact has no company opportunities yet."/>}</div></Card>}
 {tab==="Emails"&&<><Tools query={query} setQuery={setQuery} placeholder="Search subject or message"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Incoming</option><option>Outgoing</option></select></Tools><Card title="Emails" sub="Messages linked by contact ID"><div className="cx-list">{rEmails.filter(x=>matches(x)&&(filter==="All"||x.direction===filter)).map(x=><Row key={x.id} icon="E" title={x.subject} meta={`${x.direction} · ${date(x.date)}`} value={x.status} onClick={()=>open("Email",x)}/>)}{!rEmails.filter(x=>matches(x)&&(filter==="All"||x.direction===filter)).length&&<Empty icon="✉" title="No matching emails" text="Try another search or direction filter."/>}</div></Card></>}
 {tab==="Calls"&&<><Tools query={query} setQuery={setQuery} placeholder="Search calls or notes"/><Card title="Calls" sub="Conversation history for this contact"><div className="cx-list">{rCalls.filter(matches).map(x=><Row key={x.id} icon="C" title={x.title} meta={`${x.direction} · ${date(x.date)} · ${x.source}`} value={x.status} onClick={()=>open("Call",x)}/>)}{!rCalls.filter(matches).length&&<Empty icon="☎" title="No matching calls" text="Connected call records will appear here."/>}</div></Card></>}
 {tab==="Tasks"&&<><Tools query={query} setQuery={setQuery} placeholder="Search tasks"><Pills items={["All","Open","Completed","Overdue"]} value={filter} onChange={setFilter}/></Tools><Card title="Tasks" sub="Follow-ups linked through related opportunities"><div className="cx-list">{taskList.map(x=><Row key={x.id} icon="T" title={x.title} meta={`${x.priority} priority · due ${date(x.due)}`} value={x.status} task={x} onToggle={toggle} onClick={()=>open("Task",x)}/>)}{!taskList.length&&<Empty icon="✓" title="No matching tasks" text="Change the filter or search to see other follow-ups."/>}</div></Card></>}
 {tab==="Activity"&&<><Tools query={query} setQuery={setQuery} placeholder="Search activity"><Pills items={activityTypes} value={filter} onChange={setFilter}/></Tools><Card title="Activity timeline" sub="Every connected touchpoint, newest first"><div className="cx-list">{activityList.map((x,i)=><Row key={`${x.kind}-${x.record.id}-${i}`} icon={x.kind[0]} title={x.title} meta={`${x.kind} · ${date(x.date)}`} value={x.status} onClick={()=>open(x.kind,x.record)}/>)}{!activityList.length&&<Empty icon="◷" title="No matching activity" text="Try another activity type or search."/>}</div></Card></>}
 <Drawer item={detail} onClose={()=>setDetail(null)} onToggle={toggle}/>{notice&&<div className="cx-notice">✓ {notice}</div>}</div>
}
